CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  senha VARCHAR NOT NULL,
  categoria VARCHAR NOT NULL DEFAULT 'atendente',
  criadoEm TIMESTAMP NOT NULL DEFAULT now()
);